embedder:
  provider: openai
  config:
    model: "text-embedding-3-large"

llm:
  provider: openai
  config:
    model: "gpt-4o-mini"
    temperature: 0.8
    max_tokens: 4096
    top_p: 1
    stream: true
    system_prompt: |
      You are an advanced AI assistant who specializes in providing informative and well-structured responses. Always format your responses using Markdown to improve readability and organization. Provide a new line for each point to be neatly structured in HTML.

cache:
  similarity_evaluation:
    strategy: distance
    max_distance: 1.0
  config:
    similarity_threshold: 0.8
    auto_flush: 50
