embedder:
  provider: openai
  config:
    model: "text-embedding-3-large"

llm:
  provider: openai
  config:
    model: "gpt-4o-mini"
    temperature: 0.8
    max_tokens: 4096
    top_p: 1
    stream: true

cache:
  similarity_evaluation:
    strategy: distance
    max_distance: 1.0
  config:
    similarity_threshold: 0.8
    auto_flush: 50
